# Generated by Django 5.0.4 on 2026-05-11 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('mobile', '📱 Mobil'), ('tablet', '📟 Planshet'), ('desktop', '🖥 Kompyuter'), ('unknown', "❓ Noma'lum")], default='unknown', max_length=10)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os_info', models.CharField(blank=True, max_length=100)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
    ]
